version: '3'

services:
  nginx:
      image: nginx:latest
      container_name: 'nginx2'
      ports:
      - 80:80
      volumes:
        - /root/nginx/html:/usr/share/nginx/html
        - /root/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      privileged: true

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    restart: always
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/data/db
    command: mongod --directoryperdb

  mysql:
    image: mysql:latest
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=qwaszx1008612

  blockchain:
    image: blockchain:latest
    build:
      context: .
      dockerfile: Dockerfile

    container_name: blockchain
    volumes:
    - /root/blockchainData/certificateTemplate:/root/blockchainData/certificateTemplate
    - /root/blockchainData/DigitalCertificate:/root/blockchainData/DigitalCertificate
    - /root/blockchainData/HashExcel:/root/blockchainData/HashExcel
    - /root/blockchainData/picture:/root/blockchainData/picture
    ports:
    - 8181:8181
    - 6179:6179

    depends_on:
      - mysql
      - mongodb


